package com.vibe.app.feature.project.snapshot

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Pure file-system operations for snapshots. Stateless — does not know about
 * indexes, turn numbers, or project metadata.
 *
 * The `build/` directory is excluded from both dump and delete-on-restore —
 * it holds Gradle/AAPT2 intermediates that are regenerated by the next build.
 */
class SnapshotStorage {

    /**
     * Copies every file under [workspaceRoot] (excluding `build/`) into
     * `$snapshotDir/files/...` mirroring relative paths. Returns a manifest
     * listing every file included.
     */
    suspend fun dumpWorkspace(
        snapshotId: String,
        workspaceRoot: File,
        snapshotDir: File,
    ): SnapshotManifest = withContext(Dispatchers.IO) {
        val filesDir = File(snapshotDir, "files").apply { mkdirs() }
        val collected = mutableListOf<String>()

        workspaceRoot.walkTopDown()
            .onEnter { it.name != "build" }
            .filter { it.isFile }
            .forEach { src ->
                val rel = src.toRelativeString(workspaceRoot)
                val dst = File(filesDir, rel)
                dst.parentFile?.mkdirs()
                src.copyTo(dst, overwrite = true)
                collected += rel
            }

        SnapshotManifest(snapshotId = snapshotId, files = collected.sorted())
    }

    /**
     * Restores [manifest]'s files into [workspaceRoot] and deletes any workspace
     * file not in the manifest. The `build/` directory is never touched.
     */
    suspend fun restoreSnapshot(
        manifest: SnapshotManifest,
        snapshotDir: File,
        workspaceRoot: File,
    ): RestoreDiff = withContext(Dispatchers.IO) {
        val filesDir = File(snapshotDir, "files")
        val snapshotPaths = manifest.files.toSet()

        val currentPaths = workspaceRoot.walkTopDown()
            .onEnter { it.name != "build" }
            .filter { it.isFile }
            .map { it.toRelativeString(workspaceRoot) }
            .toSet()

        val toDelete = (currentPaths - snapshotPaths).sorted()
        for (rel in toDelete) {
            File(workspaceRoot, rel).delete()
        }

        val restored = mutableListOf<String>()
        for (rel in manifest.files) {
            val src = File(filesDir, rel)
            val dst = File(workspaceRoot, rel)
            dst.parentFile?.mkdirs()
            src.copyTo(dst, overwrite = true)
            restored += rel
        }

        RestoreDiff(restoredFiles = restored, deletedFiles = toDelete)
    }
}

/** In-memory result of a restore — which files were rewritten, which were deleted. */
data class RestoreDiff(
    val restoredFiles: List<String>,
    val deletedFiles: List<String>,
)
